# Generated by Django 4.0.6 on 2022-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charity_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
