# Generated by Django 4.0.6 on 2022-07-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.charity'),
        ),
    ]
