# Generated by Django 4.0.6 on 2022-08-02 11:44

import charities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0008_alter_benefactor_user_alter_charity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='reg_number',
            field=models.CharField(max_length=10, validators=[charities.validators.RegNumberValidators()]),
        ),
    ]
