# Generated by Django 4.0.6 on 2022-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
